# Generated by Django 5.1.6 on 2025-03-04 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0010_delete_atendimento'),
        ('requerimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='cliente_atendimento',
                    to='clientes.cliente')),
                ('requerimento', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='requerimento_atendimento',
                    to='requerimentos.requerimento')),
            ],
        ),
    ]
