# Generated by Django 5.1.6 on 2025-03-04 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0008_remove_documento_cliente_remove_documento_exigencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoExigencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(choices=[('em análise', 'Em Análise'), ('concluído', 'Concluído')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoRequerimentoInicial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(choices=[('em análise', 'Em Análise'), ('concluído deferido', 'Concluído Deferido'), ('concluído indeferido', 'Concluído Indeferido')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoRequerimentoRecurso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(choices=[('em análise na junta', 'Em Análise na Junta'), ('em análise no conselho', 'Em Análise no Conselho'), ('concluído', 'Concluído')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Exigencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado_exigencia', to='requerimentos.estadoexigencia')),
            ],
        ),
        migrations.CreateModel(
            name='Natureza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Requerimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('protocolo', models.CharField(max_length=20, unique=True)),
                ('NB', models.CharField(blank=True, max_length=20, null=True)),
                ('requerente_dependentes', models.TextField(blank=True, null=True)),
                ('data', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('instituidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente_instituidor_requerimento', to='clientes.cliente')),
                ('requerente_titular', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cliente_titular_requerimento', to='clientes.cliente')),
                ('tutor_curador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente_tutor_curador_requerimento', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExigenciaRequerimentoInicial',
            fields=[
                ('exigencia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='requerimentos.exigencia')),
            ],
            bases=('requerimentos.exigencia',),
        ),
        migrations.CreateModel(
            name='ExigenciaRequerimentoRecurso',
            fields=[
                ('exigencia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='requerimentos.exigencia')),
            ],
            bases=('requerimentos.exigencia',),
        ),
        migrations.AddField(
            model_name='exigencia',
            name='natureza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='natureza_exigencia', to='requerimentos.natureza'),
        ),
        migrations.AddField(
            model_name='exigencia',
            name='requerimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimento_exigencia', to='requerimentos.requerimento'),
        ),
        migrations.AddField(
            model_name='requerimento',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servico_requerimento', to='requerimentos.servico'),
        ),
        migrations.CreateModel(
            name='RequerimentoInicial',
            fields=[
                ('requerimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='requerimentos.requerimento')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado_requerimento_inicial', to='requerimentos.estadorequerimentoinicial')),
            ],
            bases=('requerimentos.requerimento',),
        ),
        migrations.CreateModel(
            name='HistoricoMudancaEstadoRequerimentoInicial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_mudanca', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('estado_anterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estado_anterior', to='requerimentos.estadorequerimentoinicial')),
                ('estado_novo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado_novo', to='requerimentos.estadorequerimentoinicial')),
                ('requerimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_estado_requerimento', to='requerimentos.requerimentoinicial')),
            ],
        ),
        migrations.CreateModel(
            name='RequerimentoRecurso',
            fields=[
                ('requerimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='requerimentos.requerimento')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado_requerimento_recurso', to='requerimentos.estadorequerimentorecurso')),
            ],
            bases=('requerimentos.requerimento',),
        ),
    ]
