# Generated by Django 5.1.1 on 2024-11-10 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_atendimento_cliente_and_more'),
        ('clientes', '0005_alter_requerimento_nb'),
    ]

    operations = [
    ]
