# Generated by Django 5.1.6 on 2025-03-04 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_atendimento_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='exigencia',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='requerimento',
        ),
        migrations.RemoveField(
            model_name='exigencia',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='requerimentoinicial',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='historicomudancaestadorequerimentoinicial',
            name='estado_novo',
        ),
        migrations.RemoveField(
            model_name='historicomudancaestadorequerimentoinicial',
            name='estado_anterior',
        ),
        migrations.RemoveField(
            model_name='requerimentorecurso',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='exigencia',
            name='natureza',
        ),
        migrations.RemoveField(
            model_name='exigencia',
            name='requerimento',
        ),
        migrations.RemoveField(
            model_name='exigenciarequerimentoinicial',
            name='exigencia_ptr',
        ),
        migrations.RemoveField(
            model_name='exigenciarequerimentorecurso',
            name='exigencia_ptr',
        ),
        migrations.RemoveField(
            model_name='historicomudancaestadorequerimentoinicial',
            name='requerimento',
        ),
        migrations.RemoveField(
            model_name='requerimento',
            name='instituidor',
        ),
        migrations.RemoveField(
            model_name='requerimento',
            name='requerente_titular',
        ),
        migrations.RemoveField(
            model_name='requerimento',
            name='servico',
        ),
        migrations.RemoveField(
            model_name='requerimento',
            name='tutor_curador',
        ),
    ]
