# Generated by Django 5.1.6 on 2025-03-04 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_remove_documento_cliente_remove_documento_exigencia_and_more'),
        ('requerimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='requerimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requerimento_atendimento', to='requerimentos.requerimento'),
        ),
        migrations.RemoveField(
            model_name='requerimentorecurso',
            name='requerimento_ptr',
        ),
        migrations.RemoveField(
            model_name='requerimentoinicial',
            name='requerimento_ptr',
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.DeleteModel(
            name='EstadoExigencia',
        ),
        migrations.DeleteModel(
            name='EstadoRequerimentoInicial',
        ),
        migrations.DeleteModel(
            name='EstadoRequerimentoRecurso',
        ),
        migrations.DeleteModel(
            name='Natureza',
        ),
        migrations.DeleteModel(
            name='ExigenciaRequerimentoInicial',
        ),
        migrations.DeleteModel(
            name='Exigencia',
        ),
        migrations.DeleteModel(
            name='ExigenciaRequerimentoRecurso',
        ),
        migrations.DeleteModel(
            name='HistoricoMudancaEstadoRequerimentoInicial',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
        migrations.DeleteModel(
            name='RequerimentoRecurso',
        ),
        migrations.DeleteModel(
            name='Requerimento',
        ),
        migrations.DeleteModel(
            name='RequerimentoInicial',
        ),
    ]
