# Generated by Django 5.1.6 on 2025-03-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_atendimento_requerimento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Atendimento',
        ),
    ]
